# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57d3d800b7e4f6a36d69a4d403af75e21df4dcf0cd0cb477e7397a01c463013fe549e5fae5b3946a7bb10cb423c9868d8a31683e9f99b4ecf54ab74a51343d39

test:
  secret_key_base: 57ea7b176879b0557c9b1ebf236cff4e3f33738152ad5b041f702a8034a04fc821dc5a6052bc74e044849e15dd72b298965f5b2186463fdf24e5f50edb3b9095

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
